/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || 'B4E643CA-9AA4-4D3E-BFF3-8E7CA14649D7';
config.sitecoreApiHost = process.env.SITECORE_API_HOST || 'https://sitecore104sc.dev.local';
config.sitecoreSiteName = process.env.SITECORE_SITE_NAME || 'arbrevamp';
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || '/sitecore/api/graph/edge';
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || 'en';
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || 'https://sitecore104sc.dev.local/sitecore/api/graph/edge';
config.layoutServiceConfigurationName = process.env.LAYOUT_SERVICE_CONFIGURATION_NAME || 'sxa-jss';
config.publicUrl = process.env.PUBLIC_URL || 'http://localhost:3000';
config.sites = process.env.SITES || '[{"name":"arbrevamp","hostName":"*","language":"en"}]';
module.exports = config;